version: "2"
services:
    docker-app-demo:
        container_name: docker_app_demo
        build: .
        user: "${UID_GID}"
        volumes:
            - ./src:/app
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            # Change hostname to `mongo`
            - MONGO_URI=mongodb://mongo:27017/test 
        networks:
            - persistentstack_common
networks:
    persistentstack_common:
        external: true